# Generated by Django 5.1.6 on 2025-03-14 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_added', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('BL', 'Black'), ('GR', 'Green'), ('WT', 'White'), ('OL', 'Oolong'), ('HB', 'Herbal'), ('MS', 'Masala'), ('CL', 'Chai Latte'), ('IC', 'Iced'), ('BB', 'Bubble')], default='MS', max_length=2)),
            ],
        ),
    ]
