# Generated by Django 5.1.6 on 2025-03-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinja', '0002_chaivariety_description_chaivariety_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivariety',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
    ]
